/**
 * ============================================================================
 * PRODUCT2VEC WEB APPLICATION
 * ============================================================================
 * 
 * This JavaScript application powers the interactive Product2Vec predictor.
 * 
 * How it works:
 * 1. Load pre-computed data (products.json, similarities.json)
 * 2. User adds products to their basket
 * 3. For each product in basket, look up its similar products
 * 4. Aggregate and rank to predict what they'll buy next
 * 
 * No heavy computation happens here - everything is pre-computed!
 * ============================================================================
 */

// =============================================================================
// GLOBAL STATE
// =============================================================================

let products = [];           // All products with metadata
let similarities = {};       // Pre-computed similar products
let basket = [];             // User's current basket
let currentFilter = null;    // Current department filter
let searchQuery = '';        // Current search query


// =============================================================================
// DATA LOADING
// =============================================================================

/**
 * Load all required JSON data files.
 * These files are generated by export_for_web.py
 */
async function loadData() {
    try {
        console.log('Loading data...');
        
        // Load products list
        const productsResponse = await fetch('web_data/products.json');
        if (!productsResponse.ok) throw new Error('Failed to load products.json');
        products = await productsResponse.json();
        console.log(`Loaded ${products.length} products`);
        
        // Load pre-computed similarities
        const similaritiesResponse = await fetch('web_data/similarities.json');
        if (!similaritiesResponse.ok) throw new Error('Failed to load similarities.json');
        similarities = await similaritiesResponse.json();
        console.log(`Loaded similarities for ${Object.keys(similarities).length} products`);
        
        // Hide loading, show main content
        document.getElementById('loading').style.display = 'none';
        document.getElementById('main-content').style.display = 'block';
        
        // Initialize UI
        initializeUI();
        
    } catch (error) {
        console.error('Error loading data:', error);
        document.getElementById('loading').innerHTML = `
            <p style="color: #ef4444;">Error loading data: ${error.message}</p>
            <p style="color: #94a3b8; margin-top: 8px;">Make sure web_data/ folder exists with products.json and similarities.json</p>
        `;
    }
}


// =============================================================================
// UI INITIALIZATION
// =============================================================================

/**
 * Initialize all UI components after data is loaded.
 */
function initializeUI() {
    renderFilters();
    renderProducts();
    setupEventListeners();
}

/**
 * Render department filter buttons.
 */
function renderFilters() {
    const filtersContainer = document.getElementById('filters');
    
    // Get unique departments
    const departments = [...new Set(products.map(p => p.department))].sort();
    
    // Add "All" button
    let html = `<button class="filter-btn active" data-department="">All</button>`;
    
    // Add department buttons
    for (const dept of departments) {
        if (dept && dept !== 'unknown') {
            html += `<button class="filter-btn" data-department="${dept}">${dept}</button>`;
        }
    }
    
    filtersContainer.innerHTML = html;
}

/**
 * Render the product grid.
 */
function renderProducts() {
    const grid = document.getElementById('products-grid');
    
    // Filter products
    let filtered = products;
    
    // Apply department filter
    if (currentFilter) {
        filtered = filtered.filter(p => p.department === currentFilter);
    }
    
    // Apply search filter
    if (searchQuery) {
        const query = searchQuery.toLowerCase();
        filtered = filtered.filter(p => 
            p.name.toLowerCase().includes(query)
        );
    }
    
    // Limit display (for performance)
    const displayProducts = filtered.slice(0, 200);
    
    // Render
    let html = '';
    for (const product of displayProducts) {
        const inBasket = basket.includes(product.name);
        html += `
            <button class="product-btn ${inBasket ? 'in-basket' : ''}" 
                    data-product="${escapeHtml(product.name)}">
                ${escapeHtml(product.name)}
            </button>
        `;
    }
    
    if (displayProducts.length === 0) {
        html = '<p style="color: #64748b; padding: 20px; text-align: center;">No products found</p>';
    }
    
    grid.innerHTML = html;
}

/**
 * Render the basket.
 */
function renderBasket() {
    const container = document.getElementById('basket-items');
    const countSpan = document.getElementById('basket-count');
    const clearBtn = document.getElementById('clear-basket');
    
    countSpan.textContent = basket.length;
    
    if (basket.length === 0) {
        container.innerHTML = '<p class="basket-empty">Click products to add them to your basket</p>';
        clearBtn.style.display = 'none';
    } else {
        clearBtn.style.display = 'flex';
        let html = '';
        for (const item of basket) {
            html += `
                <span class="basket-item">
                    ${escapeHtml(item)}
                    <span class="remove" data-product="${escapeHtml(item)}">✕</span>
                </span>
            `;
        }
        container.innerHTML = html;
    }
    
    // Update predictions
    renderPredictions();
    
    // Update product grid to show which items are in basket
    renderProducts();
}

/**
 * Render predictions based on current basket.
 * 
 * PREDICTION ALGORITHM:
 * 1. For each product in basket, get its pre-computed similar products
 * 2. Aggregate scores (products that are similar to MULTIPLE basket items score higher)
 * 3. Exclude products already in basket
 * 4. Sort by score and show top 10
 */
function renderPredictions() {
    const container = document.getElementById('predictions');
    
    if (basket.length === 0) {
        container.innerHTML = '<p class="predictions-empty">Add items to see AI predictions</p>';
        return;
    }
    
    // Aggregate similarities from all basket items
    const scores = {};
    
    for (const basketItem of basket) {
        // Get pre-computed similar products for this item
        const similar = similarities[basketItem] || [];
        
        for (const [productName, score] of similar) {
            // Skip if already in basket
            if (basket.includes(productName)) continue;
            
            // Add to aggregated score
            // Products similar to MULTIPLE basket items get higher scores
            if (!scores[productName]) {
                scores[productName] = 0;
            }
            scores[productName] += score;
        }
    }
    
    // Convert to array and sort by score
    const predictions = Object.entries(scores)
        .map(([name, score]) => ({ name, score }))
        .sort((a, b) => b.score - a.score)
        .slice(0, 10);
    
    if (predictions.length === 0) {
        container.innerHTML = '<p class="predictions-empty">No predictions available for these items</p>';
        return;
    }
    
    // Find max score for normalization
    const maxScore = predictions[0].score;
    
    // Render
    let html = '';
    for (let i = 0; i < predictions.length; i++) {
        const pred = predictions[i];
        const normalizedScore = pred.score / maxScore;
        const percentage = Math.round(normalizedScore * 100);
        
        html += `
            <div class="prediction-item" data-product="${escapeHtml(pred.name)}">
                <span class="prediction-rank">${i + 1}</span>
                <span class="prediction-name">${escapeHtml(pred.name)}</span>
                <div class="prediction-score">
                    <div class="score-bar">
                        <div class="score-bar-fill" style="width: ${percentage}%"></div>
                    </div>
                    <span class="score-text">${percentage}%</span>
                </div>
            </div>
        `;
    }
    
    container.innerHTML = html;
}


// =============================================================================
// EVENT LISTENERS
// =============================================================================

/**
 * Set up all event listeners.
 */
function setupEventListeners() {
    // Search input
    const searchInput = document.getElementById('search-input');
    searchInput.addEventListener('input', (e) => {
        searchQuery = e.target.value;
        renderProducts();
    });
    
    // Filter buttons (event delegation)
    document.getElementById('filters').addEventListener('click', (e) => {
        if (e.target.classList.contains('filter-btn')) {
            // Update active state
            document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
            e.target.classList.add('active');
            
            // Update filter
            currentFilter = e.target.dataset.department || null;
            renderProducts();
        }
    });
    
    // Product buttons (event delegation)
    document.getElementById('products-grid').addEventListener('click', (e) => {
        const btn = e.target.closest('.product-btn');
        if (btn) {
            const productName = btn.dataset.product;
            toggleBasketItem(productName);
        }
    });
    
    // Basket item remove buttons (event delegation)
    document.getElementById('basket-items').addEventListener('click', (e) => {
        if (e.target.classList.contains('remove')) {
            const productName = e.target.dataset.product;
            removeFromBasket(productName);
        }
    });
    
    // Clear basket button
    document.getElementById('clear-basket').addEventListener('click', () => {
        basket = [];
        renderBasket();
    });
    
    // Prediction items (click to add to basket)
    document.getElementById('predictions').addEventListener('click', (e) => {
        const item = e.target.closest('.prediction-item');
        if (item) {
            const productName = item.dataset.product;
            addToBasket(productName);
        }
    });
}


// =============================================================================
// BASKET MANAGEMENT
// =============================================================================

/**
 * Toggle a product in/out of the basket.
 */
function toggleBasketItem(productName) {
    if (basket.includes(productName)) {
        removeFromBasket(productName);
    } else {
        addToBasket(productName);
    }
}

/**
 * Add a product to the basket.
 */
function addToBasket(productName) {
    if (!basket.includes(productName)) {
        basket.push(productName);
        renderBasket();
    }
}

/**
 * Remove a product from the basket.
 */
function removeFromBasket(productName) {
    basket = basket.filter(item => item !== productName);
    renderBasket();
}


// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Escape HTML to prevent XSS.
 */
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}


// =============================================================================
// INITIALIZATION
// =============================================================================

// Load data when page loads
document.addEventListener('DOMContentLoaded', loadData);
